import logging
import asyncio
from . import logger_config

from dotenv import load_dotenv

from livekit.agents import (
    Agent,
    AgentServer,
    AgentSession,
    JobContext,
    JobProcess,
    MetricsCollectedEvent,
    RunContext,
    cli,
    metrics,
    room_io,
    llm,
)
from livekit.plugins import silero
# Integration imports
from app.agent.sales_llm import SalesLLM
from app.agent.prompts import DETERMINISTIC_SYSTEM_PROMPT
from livekit.plugins.turn_detector.multilingual import MultilingualModel

logger = logging.getLogger("basic-agent")

load_dotenv()


class MyAgent(Agent):
    def __init__(self) -> None:
        super().__init__(
            instructions=DETERMINISTIC_SYSTEM_PROMPT,
        )

    async def on_enter(self):
        # Initial greeting generated by SalesAgent
        self.session.generate_reply(allow_interruptions=False)


server = AgentServer()


def prewarm(proc: JobProcess):
    proc.userdata["vad"] = silero.VAD.load()


server.setup_fnc = prewarm


@server.rtc_session()
async def entrypoint(ctx: JobContext):
    ctx.log_context_fields = {
        "room": ctx.room.name,
    }

    # Session ID corresponds to room name for memory persistence
    session_id = ctx.room.name
    
    session = AgentSession(
        stt="deepgram/nova-3",
        # worker.py acts only as an orchestrator. SalesAgent acts as the brain.
        llm=SalesLLM(session_id),
        tts="cartesia/sonic-2:9626c31c-bec5-4cca-baa8-f8ba9e84c8bc",
        turn_detection=MultilingualModel(),
        vad=ctx.proc.userdata["vad"],
        min_endpointing_delay=0.4, # Start thinking 400ms after user pauses
        preemptive_generation=True,
        resume_false_interruption=True,
        false_interruption_timeout=1.2, # Recover faster from accidental interruptions
    )

    usage_collector = metrics.UsageCollector()

    @session.on("metrics_collected")
    def _on_metrics_collected(ev: MetricsCollectedEvent):
        metrics.log_metrics(ev.metrics)
        usage_collector.collect(ev.metrics)

    async def log_usage():
        summary = usage_collector.get_summary()
        logger.info(f"Usage: {summary}")

    ctx.add_shutdown_callback(log_usage)

    await session.start(
        agent=MyAgent(),
        room=ctx.room,
        room_options=room_io.RoomOptions(
            audio_input=room_io.AudioInputOptions(),
        ),
    )



if __name__ == "__main__":
    cli.run_app(server)